name: Trigger Django Rest Backend Test Runner

on:
  pull_request_target:
    branches: ["main"]

jobs:
  django_rest_backend_test_runner:
    uses: developer-job-simulation/django-rest-backend-tests/.github/workflows/main.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} 
